auth/urls.py
from django.urls import path
from auth import views

urlpatterns = [
    path('login', views.Login.as_view()),
    path('logout', views.Logout.as_view()),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('college/<int:pk>', views.CollegeDetail.as_view()),
    path('college_create', views.CollegeCreate.as_view()),
    path('college_update/<int:pk>', views.CollegeUpdate.as_view()),
    path('college_delete/<int:pk>', views.CollegeDelete.as_view()),
    path('', views.index)
]

main/models.py
from django.db import models

# Create your models here.
class College(models.Model):
    name = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length = 256)
    rollno = models.IntegerField()
    college = models.ForeignKey('College', on_delete = models.CASCADE)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from main import models
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.decorators import login_required

@login_required(login_url = '/auth/login')
def index(request):
    colleges = models.College.objects.all()
    context = {
        "colleges":colleges
    }
    return render(request, 'index.html', context)


class Index(ListView):
    model = models.College
    template_name = 'index.html'
    context_object_name = 'colleges'

def collegeDetail(request, pk):
    colleges = models.College.objects.get(pk = pk)
    context = {
        "colleges":colleges
    }
    return render(request, 'collegeDetail.html', context)

class CollegeDetail(DetailView):
    model = models.College
    template_name = 'collegeDetail.html'
    context_object_name = 'colleges'

class CollegeCreate(CreateView):
    model = models.College
    template_name = 'createCollege.html'
    fields = '__all__'
    success_url = '/'

class CollegeUpdate(UpdateView):
    model = models.College
    template_name = 'createCollege.html'
    fields = '__all__'
    success_url = '/'

class CollegeDelete(DeleteView):
    model = models.College
    template_name = 'collge_delete.html'
    success_url = '/'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block con %} {% endblock %}
</body>
</html>

templates/collegeDetail.html
{% extends 'base.html' %}

{% block con %}
    <h1>{{colleges.name}}</h1>
    {% for college in colleges.student_set.all %}
        <li>{{college.name}}</li>
    {% endfor %}
{% endblock %}

templates/collge_delete.html
{% extends 'base.html' %}

{% block con %}
    <form method="POST">
        {% csrf_token %}
        Are u sure u want to delete?
        <button type="reset"> No </button>
        <button type="submit">Yes</button>
    </form>
{% endblock %}

templates/createCollege.html
{% extends 'base.html' %}

{% block con %}
    <h1>Create Colleg</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">Create</button>
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block con %}
    <h1>List of Colleges</h1>
    {% for college in colleges %}
        <li>{{college.name}}</li>
    {% endfor %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block con %}
    {% if error %}
        {{error}}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">Login</button>
    </form>
{% endblock %}